version: "3.7"

networks:
  test:
    name: fabric_test

services:
  peer0.subhra.example.com:
    container_name: peer0.subhra.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg/:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}/:/host/var/run/docker.sock
